// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgnttrxhbmnpyntbgmvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnbnR0cnhoYm1ucHludGJnbXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjc0MzksImV4cCI6MjA2NjYwMzQzOX0.G2SiFlosu4rBDD5K-L1ZaYG9h0uS-CUfSlo1deY606A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);